import type { Metadata } from "next";
import { Lato } from "next/font/google";
import { ReactNode } from "react";
import Providers from "./providers";

const inter = Lato({ weight: "400", style: "normal", subsets: ["latin-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
